# site
title: Cardtoken Doc & API Reference.
description: Provides the developer and API Reference documentation.
locale: en-us
theme: jekyll-theme-cayman

# Jekyll
permalink:          /:title/
markdown:           kramdown
highlighter:        rouge

plugins:
  - jekyll-relative-links
  - jekyll-seo-tag
  - jekyll-sitemap
relative_links:
  enabled: true
  collections: true
include:
  - index.md
# List of links in the navigation bar
navbar-links:
  Getting Started: "getting-started"
  About Me: "aboutme"
  Resources:
    - Beautiful Jekyll: "http://deanattali.com/beautiful-jekyll/"
    - Learn markdown: "http://www.markdowntutorial.com/"
    - GitHub Pages: "https://pages.github.com/"
  Author's home: "http://deanattali.com"
